# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rtlabs"
BBFILE_PATTERN_rtlabs = "^${LAYERDIR}/"
BBFILE_PRIORITY_rtlabs = "6"

PREFERRED_PROVIDER_p-net = "p-net-evaluation"

LICENSE_PATH += "${LAYERDIR}/licenses"
SPDXLICENSEMAP[LicenseRef-RT-Labs-Deployment-1.0] = "RT-Labs-Deployment-1.0"
